### ISSUE TITLE
option to keep certain number of kernels

### ISSUE THREAD

**Issue by si458** [jordanhillis/pvekclean#2]
it would be amazing if the module had an option to allow it to keep back a certain number of kernels

currently it removes all old kernela excluding the latest you have installed OR the latest one if you havent restarted yet to apply it

an option like maybe `--keep 3` to say keep the 3 latest kernels

**Comment by sibelle-labs** [comment]
I agree with you

**Comment by si458** [comment]
anybody looks for this feature
a fork has implemented this feature to leave behind 2 kernels for recovery purposes - https://github.com/rhyven/pvekclean

**Comment by jordanhillis** [comment]
This feature has been added to version 1.3 (just released). Thank you all for your patience with this being added.
