### ISSUE TITLE
Remove New Kernel

### ISSUE THREAD

**Issue by nicedevil007** [jordanhillis/pvekclean#3]
Heya, thank you for this awesome package. 

Unfortunately I dont want to remove an old kernel, I want to remove a the new kernel... Why, proxmox isn't shutting down or booting up with the latest kernel :(

It is 100% reproducable.

Your script only allows the uninstallation of old kernels :(

![image](https://user-images.githubusercontent.com/17103076/144742147-5babfe14-9e47-4de7-8f82-6cc5bd8893c8.png)

**Comment by jordanhillis** [comment]
Hey @nicedevil007 thanks for your feature request! 

I have added this to version 1.3. 
Check it out in the latest release.
