### ISSUE TITLE
New Proxmox Kernal Prefix in comming.

### ISSUE THREAD

**Issue by Shuazijun** [jordanhillis/pvekclean#6]
update log:  
proxmox-kernel-6.2 (6.2.16-7) bookworm; urgency=medium  
  
  * change `pve-` prefix to `proxmox-`  
  
  * merge proxmox-kernel-meta packaging into main kernel repository  
  
  * bump ABI to 6.2.16-6

**Comment by jordanhillis** [comment]
Thank you for informing me! I have made the changes to version 1.3 to reflect this change from Proxmox.
